# Generated by Django 5.0.6 on 2024-05-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_order_order_id_alter_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
