# Generated by Django 5.0.6 on 2024-05-27 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_alter_order_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSpeedaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_order_no', models.CharField(max_length=255, unique=True)),
                ('customer_code', models.CharField(max_length=255)),
                ('platform_source', models.CharField(max_length=255)),
                ('parcel_type', models.CharField(max_length=255)),
                ('delivery_type', models.CharField(max_length=255)),
                ('transport_type', models.CharField(max_length=255)),
                ('ship_type', models.CharField(max_length=255)),
                ('pay_method', models.CharField(max_length=255)),
                ('accept_name', models.CharField(max_length=255)),
                ('accept_mobile', models.CharField(max_length=255)),
                ('accept_address', models.CharField(max_length=255)),
                ('accept_country_code', models.CharField(max_length=255)),
                ('accept_province_name', models.CharField(max_length=255)),
                ('accept_city_name', models.CharField(max_length=255)),
                ('accept_district_name', models.CharField(max_length=255)),
                ('send_name', models.CharField(max_length=255)),
                ('send_address', models.CharField(max_length=255)),
                ('send_mobile', models.CharField(max_length=255)),
                ('send_country_code', models.CharField(max_length=255)),
                ('send_province_name', models.CharField(max_length=255)),
                ('send_city_name', models.CharField(max_length=255)),
                ('send_district_name', models.CharField(max_length=255)),
                ('parcel_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('piece', models.IntegerField()),
                ('goods_qty', models.IntegerField()),
                ('tax_method', models.CharField(max_length=255)),
                ('pick_up_aging', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductsSpeedaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('goods_name', models.CharField(max_length=255)),
                ('goods_name_dialect', models.CharField(max_length=255)),
                ('goods_qty', models.IntegerField()),
                ('goods_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goods_type', models.CharField(max_length=255)),
                ('bl_insure', models.IntegerField()),
                ('battery', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.orderspeedaf', to_field='custom_order_no')),
            ],
        ),
    ]
